apiVersion: v1
kind: Secret
metadata:
  name: jobvacancysecret
  labels:
    app: jobvacancy

stringData:
  DATABASE_URL: postgresql://postgres:"A COMPLETAR"@jobvacancydb:8081/jobvacancy
  POSTGRES_DB: jobvacancy
  POSTGRES_PASSWORD: "A COMPLETAR"
