apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordapi
  labels:
    app: passwordapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordapi
  template:
    metadata:
      labels:
        app: passwordapi
    spec:
      containers:
      - name: webapp
        image: nicopaez/password-api:1.5.0-java
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
