kind: Service
apiVersion: v1
metadata:
  name: passwordapi
  labels:
    app: passwordapi
spec:
  selector:
    app: passwordapi
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3000
  type: NodePort
