version: '3.9'
services:
  service1:
    image: nicopaez/password-api:latest

  service2:
    image: nicopaez/password-api:latest
  
  nginx:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - service1
      - service2
